package com.cailutong.app.zlot;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "REGULAR_HOLD_INFO".
 */
public class RegularHoldInfo {

    private Integer periods;
    private String ccpId;
    private Double nextAmount;
    private String ccpName;
    private Double totalInterest;
    private Integer type;
    private String subTime;
    private Integer ccsId;
    private Double amount;
    private Double yearYieldRate;
    private Double yieldRate;
    private String lastReturnTime;
    private String subTimeYMD;
    private Double settleInertest;
    private Double noSettleIntertest;
    private String nextReturnTime;

    public RegularHoldInfo() {
    }

    public RegularHoldInfo(Integer periods, String ccpId, Double nextAmount, String ccpName, Double totalInterest, Integer type, String subTime, Integer ccsId, Double amount, Double yearYieldRate, Double yieldRate, String lastReturnTime, String subTimeYMD, Double settleInertest, Double noSettleIntertest, String nextReturnTime) {
        this.periods = periods;
        this.ccpId = ccpId;
        this.nextAmount = nextAmount;
        this.ccpName = ccpName;
        this.totalInterest = totalInterest;
        this.type = type;
        this.subTime = subTime;
        this.ccsId = ccsId;
        this.amount = amount;
        this.yearYieldRate = yearYieldRate;
        this.yieldRate = yieldRate;
        this.lastReturnTime = lastReturnTime;
        this.subTimeYMD = subTimeYMD;
        this.settleInertest = settleInertest;
        this.noSettleIntertest = noSettleIntertest;
        this.nextReturnTime = nextReturnTime;
    }

    public Integer getPeriods() {
        return periods;
    }

    public void setPeriods(Integer periods) {
        this.periods = periods;
    }

    public String getCcpId() {
        return ccpId;
    }

    public void setCcpId(String ccpId) {
        this.ccpId = ccpId;
    }

    public Double getNextAmount() {
        return nextAmount;
    }

    public void setNextAmount(Double nextAmount) {
        this.nextAmount = nextAmount;
    }

    public String getCcpName() {
        return ccpName;
    }

    public void setCcpName(String ccpName) {
        this.ccpName = ccpName;
    }

    public Double getTotalInterest() {
        return totalInterest;
    }

    public void setTotalInterest(Double totalInterest) {
        this.totalInterest = totalInterest;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getSubTime() {
        return subTime;
    }

    public void setSubTime(String subTime) {
        this.subTime = subTime;
    }

    public Integer getCcsId() {
        return ccsId;
    }

    public void setCcsId(Integer ccsId) {
        this.ccsId = ccsId;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public Double getYearYieldRate() {
        return yearYieldRate;
    }

    public void setYearYieldRate(Double yearYieldRate) {
        this.yearYieldRate = yearYieldRate;
    }

    public Double getYieldRate() {
        return yieldRate;
    }

    public void setYieldRate(Double yieldRate) {
        this.yieldRate = yieldRate;
    }

    public String getLastReturnTime() {
        return lastReturnTime;
    }

    public void setLastReturnTime(String lastReturnTime) {
        this.lastReturnTime = lastReturnTime;
    }

    public String getSubTimeYMD() {
        return subTimeYMD;
    }

    public void setSubTimeYMD(String subTimeYMD) {
        this.subTimeYMD = subTimeYMD;
    }

    public Double getSettleInertest() {
        return settleInertest;
    }

    public void setSettleInertest(Double settleInertest) {
        this.settleInertest = settleInertest;
    }

    public Double getNoSettleIntertest() {
        return noSettleIntertest;
    }

    public void setNoSettleIntertest(Double noSettleIntertest) {
        this.noSettleIntertest = noSettleIntertest;
    }

    public String getNextReturnTime() {
        return nextReturnTime;
    }

    public void setNextReturnTime(String nextReturnTime) {
        this.nextReturnTime = nextReturnTime;
    }

}
