package com.cailutong.app.zlot;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cailutong.app.zlot.RegularHoldInfo;
import com.cailutong.app.zlot.RegularSettleInfo;

import com.cailutong.app.zlot.RegularHoldInfoDao;
import com.cailutong.app.zlot.RegularSettleInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig regularHoldInfoDaoConfig;
    private final DaoConfig regularSettleInfoDaoConfig;

    private final RegularHoldInfoDao regularHoldInfoDao;
    private final RegularSettleInfoDao regularSettleInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        regularHoldInfoDaoConfig = daoConfigMap.get(RegularHoldInfoDao.class).clone();
        regularHoldInfoDaoConfig.initIdentityScope(type);

        regularSettleInfoDaoConfig = daoConfigMap.get(RegularSettleInfoDao.class).clone();
        regularSettleInfoDaoConfig.initIdentityScope(type);

        regularHoldInfoDao = new RegularHoldInfoDao(regularHoldInfoDaoConfig, this);
        regularSettleInfoDao = new RegularSettleInfoDao(regularSettleInfoDaoConfig, this);

        registerDao(RegularHoldInfo.class, regularHoldInfoDao);
        registerDao(RegularSettleInfo.class, regularSettleInfoDao);
    }
    
    public void clear() {
        regularHoldInfoDaoConfig.getIdentityScope().clear();
        regularSettleInfoDaoConfig.getIdentityScope().clear();
    }

    public RegularHoldInfoDao getRegularHoldInfoDao() {
        return regularHoldInfoDao;
    }

    public RegularSettleInfoDao getRegularSettleInfoDao() {
        return regularSettleInfoDao;
    }

}
