package com.cailutong.app.zlot;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.cailutong.app.zlot.RegularHoldInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "REGULAR_HOLD_INFO".
*/
public class RegularHoldInfoDao extends AbstractDao<RegularHoldInfo, Void> {

    public static final String TABLENAME = "REGULAR_HOLD_INFO";

    /**
     * Properties of entity RegularHoldInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Periods = new Property(0, Integer.class, "periods", false, "PERIODS");
        public final static Property CcpId = new Property(1, String.class, "ccpId", false, "CCP_ID");
        public final static Property NextAmount = new Property(2, Double.class, "nextAmount", false, "NEXT_AMOUNT");
        public final static Property CcpName = new Property(3, String.class, "ccpName", false, "CCP_NAME");
        public final static Property TotalInterest = new Property(4, Double.class, "totalInterest", false, "TOTAL_INTEREST");
        public final static Property Type = new Property(5, Integer.class, "type", false, "TYPE");
        public final static Property SubTime = new Property(6, String.class, "subTime", false, "SUB_TIME");
        public final static Property CcsId = new Property(7, Integer.class, "ccsId", false, "CCS_ID");
        public final static Property Amount = new Property(8, Double.class, "amount", false, "AMOUNT");
        public final static Property YearYieldRate = new Property(9, Double.class, "yearYieldRate", false, "YEAR_YIELD_RATE");
        public final static Property YieldRate = new Property(10, Double.class, "yieldRate", false, "YIELD_RATE");
        public final static Property LastReturnTime = new Property(11, String.class, "lastReturnTime", false, "LAST_RETURN_TIME");
        public final static Property SubTimeYMD = new Property(12, String.class, "subTimeYMD", false, "SUB_TIME_YMD");
        public final static Property SettleInertest = new Property(13, Double.class, "settleInertest", false, "SETTLE_INERTEST");
        public final static Property NoSettleIntertest = new Property(14, Double.class, "noSettleIntertest", false, "NO_SETTLE_INTERTEST");
        public final static Property NextReturnTime = new Property(15, String.class, "nextReturnTime", false, "NEXT_RETURN_TIME");
    };


    public RegularHoldInfoDao(DaoConfig config) {
        super(config);
    }
    
    public RegularHoldInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"REGULAR_HOLD_INFO\" (" + //
                "\"PERIODS\" INTEGER," + // 0: periods
                "\"CCP_ID\" TEXT," + // 1: ccpId
                "\"NEXT_AMOUNT\" REAL," + // 2: nextAmount
                "\"CCP_NAME\" TEXT," + // 3: ccpName
                "\"TOTAL_INTEREST\" REAL," + // 4: totalInterest
                "\"TYPE\" INTEGER," + // 5: type
                "\"SUB_TIME\" TEXT," + // 6: subTime
                "\"CCS_ID\" INTEGER," + // 7: ccsId
                "\"AMOUNT\" REAL," + // 8: amount
                "\"YEAR_YIELD_RATE\" REAL," + // 9: yearYieldRate
                "\"YIELD_RATE\" REAL," + // 10: yieldRate
                "\"LAST_RETURN_TIME\" TEXT," + // 11: lastReturnTime
                "\"SUB_TIME_YMD\" TEXT," + // 12: subTimeYMD
                "\"SETTLE_INERTEST\" REAL," + // 13: settleInertest
                "\"NO_SETTLE_INTERTEST\" REAL," + // 14: noSettleIntertest
                "\"NEXT_RETURN_TIME\" TEXT);"); // 15: nextReturnTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REGULAR_HOLD_INFO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RegularHoldInfo entity) {
        stmt.clearBindings();
 
        Integer periods = entity.getPeriods();
        if (periods != null) {
            stmt.bindLong(1, periods);
        }
 
        String ccpId = entity.getCcpId();
        if (ccpId != null) {
            stmt.bindString(2, ccpId);
        }
 
        Double nextAmount = entity.getNextAmount();
        if (nextAmount != null) {
            stmt.bindDouble(3, nextAmount);
        }
 
        String ccpName = entity.getCcpName();
        if (ccpName != null) {
            stmt.bindString(4, ccpName);
        }
 
        Double totalInterest = entity.getTotalInterest();
        if (totalInterest != null) {
            stmt.bindDouble(5, totalInterest);
        }
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(6, type);
        }
 
        String subTime = entity.getSubTime();
        if (subTime != null) {
            stmt.bindString(7, subTime);
        }
 
        Integer ccsId = entity.getCcsId();
        if (ccsId != null) {
            stmt.bindLong(8, ccsId);
        }
 
        Double amount = entity.getAmount();
        if (amount != null) {
            stmt.bindDouble(9, amount);
        }
 
        Double yearYieldRate = entity.getYearYieldRate();
        if (yearYieldRate != null) {
            stmt.bindDouble(10, yearYieldRate);
        }
 
        Double yieldRate = entity.getYieldRate();
        if (yieldRate != null) {
            stmt.bindDouble(11, yieldRate);
        }
 
        String lastReturnTime = entity.getLastReturnTime();
        if (lastReturnTime != null) {
            stmt.bindString(12, lastReturnTime);
        }
 
        String subTimeYMD = entity.getSubTimeYMD();
        if (subTimeYMD != null) {
            stmt.bindString(13, subTimeYMD);
        }
 
        Double settleInertest = entity.getSettleInertest();
        if (settleInertest != null) {
            stmt.bindDouble(14, settleInertest);
        }
 
        Double noSettleIntertest = entity.getNoSettleIntertest();
        if (noSettleIntertest != null) {
            stmt.bindDouble(15, noSettleIntertest);
        }
 
        String nextReturnTime = entity.getNextReturnTime();
        if (nextReturnTime != null) {
            stmt.bindString(16, nextReturnTime);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public RegularHoldInfo readEntity(Cursor cursor, int offset) {
        RegularHoldInfo entity = new RegularHoldInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // periods
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ccpId
            cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2), // nextAmount
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ccpName
            cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4), // totalInterest
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // type
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // subTime
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // ccsId
            cursor.isNull(offset + 8) ? null : cursor.getDouble(offset + 8), // amount
            cursor.isNull(offset + 9) ? null : cursor.getDouble(offset + 9), // yearYieldRate
            cursor.isNull(offset + 10) ? null : cursor.getDouble(offset + 10), // yieldRate
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // lastReturnTime
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // subTimeYMD
            cursor.isNull(offset + 13) ? null : cursor.getDouble(offset + 13), // settleInertest
            cursor.isNull(offset + 14) ? null : cursor.getDouble(offset + 14), // noSettleIntertest
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15) // nextReturnTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RegularHoldInfo entity, int offset) {
        entity.setPeriods(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setCcpId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNextAmount(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
        entity.setCcpName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTotalInterest(cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4));
        entity.setType(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setSubTime(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCcsId(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setAmount(cursor.isNull(offset + 8) ? null : cursor.getDouble(offset + 8));
        entity.setYearYieldRate(cursor.isNull(offset + 9) ? null : cursor.getDouble(offset + 9));
        entity.setYieldRate(cursor.isNull(offset + 10) ? null : cursor.getDouble(offset + 10));
        entity.setLastReturnTime(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setSubTimeYMD(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setSettleInertest(cursor.isNull(offset + 13) ? null : cursor.getDouble(offset + 13));
        entity.setNoSettleIntertest(cursor.isNull(offset + 14) ? null : cursor.getDouble(offset + 14));
        entity.setNextReturnTime(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(RegularHoldInfo entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(RegularHoldInfo entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
