package com.cailutong.app.zlot;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "REGULAR_SETTLE_INFO".
 */
public class RegularSettleInfo {

    private Integer periods;
    private String ccpId;
    private String ccpName;
    private String subTime;
    private Double yearYieldRate;
    private Double yieldRate;
    private Double amount;
    private Double totalInterest;
    private String lastReturnTime;
    private Integer type;

    public RegularSettleInfo() {
    }

    public RegularSettleInfo(Integer periods, String ccpId, String ccpName, String subTime, Double yearYieldRate, Double yieldRate, Double amount, Double totalInterest, String lastReturnTime, Integer type) {
        this.periods = periods;
        this.ccpId = ccpId;
        this.ccpName = ccpName;
        this.subTime = subTime;
        this.yearYieldRate = yearYieldRate;
        this.yieldRate = yieldRate;
        this.amount = amount;
        this.totalInterest = totalInterest;
        this.lastReturnTime = lastReturnTime;
        this.type = type;
    }

    public Integer getPeriods() {
        return periods;
    }

    public void setPeriods(Integer periods) {
        this.periods = periods;
    }

    public String getCcpId() {
        return ccpId;
    }

    public void setCcpId(String ccpId) {
        this.ccpId = ccpId;
    }

    public String getCcpName() {
        return ccpName;
    }

    public void setCcpName(String ccpName) {
        this.ccpName = ccpName;
    }

    public String getSubTime() {
        return subTime;
    }

    public void setSubTime(String subTime) {
        this.subTime = subTime;
    }

    public Double getYearYieldRate() {
        return yearYieldRate;
    }

    public void setYearYieldRate(Double yearYieldRate) {
        this.yearYieldRate = yearYieldRate;
    }

    public Double getYieldRate() {
        return yieldRate;
    }

    public void setYieldRate(Double yieldRate) {
        this.yieldRate = yieldRate;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public Double getTotalInterest() {
        return totalInterest;
    }

    public void setTotalInterest(Double totalInterest) {
        this.totalInterest = totalInterest;
    }

    public String getLastReturnTime() {
        return lastReturnTime;
    }

    public void setLastReturnTime(String lastReturnTime) {
        this.lastReturnTime = lastReturnTime;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
